name: customer_app
description: Gofarm platform for customer to booking farmstay.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^4.6.16
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.2

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
