name: customer_app
description: Gofarm platform for customer to booking farmstay.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^4.6.16
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # FIREBASE
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.4.0
  fpdart: ^0.5.0
  logger: ^1.3.0
  google_sign_in: ^6.1.0

  # COMMON
  navigation_history_observer: ^1.1.0
  flutter_native_splash: ^2.2.19
  intl: ^0.17.0
  shimmer: ^2.0.0
  flutter_vector_icons: ^2.0.0
  syncfusion_flutter_datepicker: ^21.1.39

  flutter_localizations:
    sdk: flutter
  tuple: ^2.0.1
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.7
  shared_preferences: ^2.1.0
  timeago: ^3.3.0
  date_time_picker: ^2.1.0
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_native_splash:
  color: "#ffffff"
  image: "images/brand/icon.png"
  background_image: "images/brand/splash_bg.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/brand/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/brand/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/brand/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/brand/icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
    - images/brand/
    - images/stockMarket/icons/
    - images/stockMarket/stock/
    - images/shophop/
    - images/eventApp/
    - images/app/