// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTANRkV_5c7EDf0HzR38YPRxAHbQqXRU',
    appId: '1:238098794310:android:6e20c264504ea05c3a8747',
    messagingSenderId: '238098794310',
    projectId: 'go-gofarm',
    storageBucket: 'go-gofarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjgORu8jT0k6Z-eQffUFDChLiEVHWc45M',
    appId: '1:238098794310:ios:9181d4c7806ffc3b3a8747',
    messagingSenderId: '238098794310',
    projectId: 'go-gofarm',
    storageBucket: 'go-gofarm.appspot.com',
    androidClientId: '238098794310-f4mtj7t2v6aiq6a7i9umm46t2gbdl9cp.apps.googleusercontent.com',
    iosClientId: '238098794310-5bfh4fggh5sod7444pqq7ksmshttfgto.apps.googleusercontent.com',
    iosBundleId: 'gofarm.customerApp',
  );
}
